bannedWords:
  - shit
  - sh!t
  - nigger
  - n!gger
  - n!gg3r
  - nlgger
  - nlgg3r
  - n1gger
  - n1gg3r
  - niger
  - n1ger
  - nigga
  - n1gga
  - nigers
  - niggers
  - niggas
  - n1ggas
  - ni99as
  - ni9as
  - ni99a
  - ni9a
  - ni99er
  - ni9er
  - ni99ers
  - ni9ers
  - fuck
  - fvck
  - fuk
  - fvk
  - fukk
  - fukn
  - fukkn
  - fukken
  - bitch
  - b1tch
  - bltch
  - bicth
  - b1cth
  - dick
  - d1ck
  - dik
  - dic
  - d1c
  - ashole
  - azzhole
  - azz
  - nigar
  - niger
  - c0ck
  - cock
  - penis
  - vegina
  - vejina
  - vajina
  - muzerfucer
  - kock
  - k0ck
  - f0k
  - fock
  - fok
  - foc
  - kys
  - fuck
  - cunt
  - cvnt
  - dickhead
  - asshole
  - arsehole
  - fuckhead
  - fag
  - fags
  - faggot
  - faggots
  - feggit
  - feggits
  - faggit
  - faggits
  - cunts
  - kkk
  - whore
  - whores
  - slut
  - sluts
  - cunt
  - cunts
  - dickhead
  - dickheads
  - fucktard
  - fucker
  - fuckerrs
  - fvckers
  - fckkers
  - whale cum
  - whalecum
  - fuck you
  - pussy
  - cock
  - dick
  - twat
  - jack off
  - hump
  - you suck
  - whitey
  - red neck
  - redneck
  - red necks
  - rednecks
  - chingchong
  - darky
  - darkey
  - darkie
  - darkies
  - darkys
  - darkeys
  - redskin
  - redskins
  - squinty
  - tacohead
  - anal
  - bastard
  - blowjob
  - boner
  - boob
  - boobs
  - boobies
  - boobeez
  - boobiez
  - boobz
  - tit
  - tits
  - titties
  - dildo
  - gay
  - queer
  - vagina
  - whore
  - cum
  - heil
  - sex
  - piss off
  - bitch
  - fap
  - rape
  - raped
  - tirowka
  - tirówka
  - pierdol
  - jebac
  - Jebac
  - jebać
  - Jebać
  - JEBAĆ
  - JEBAC
  - huj
  - zjebany
  - sram
  - zesra
  - k,urwa
  - ku,rwa
  - kur,wa
  - kurw,a
  - kurrwa
  - kurrrwa
  - kurrrrwa
  - kurwy
  - kurew
  - kurw
  - kurwie
  - kurwom
  - kurwę
  - kurwy
  - kurwą
  - kurwami
  - kurwach
  - kurwo
  - kurwy
  - k.u.r.w.a
  - kurva
  - japierdole
  - japierd
  - pierole
  - pierdolić
  - jebię
  - jebiesz
  - jebie
  - jebiemy
  - jebiecie
  - jebią
  - jebałem
  - jebałam
  - jebałeś
  - jebałaś
  - jebał
  - jebała
  - jebało
  - jebaliśmy
  - jebałyśmy
  - jebaliście
  - jebałyście
  - jebali
  - jebały
  - będę jebał
  - będę jebała
  - będziesz jebał
  - będziesz jebała
  - będzie jebał
  - będzie jebała
  - będzie jebało
  - będziemy jebali
  - będziemy jebały
  - będziecie jebali
  - będziecie jebały
  - będą jebali
  - będą jebały
  - jebałbym
  - jebałabym
  - jebałbyś
  - jebałabyś
  - jebałby
  - jebałaby
  - jebałoby
  - jebalibyśmy
  - jebałybyśmy
  - jebalibyście
  - jebałybyście
  - jebaliby
  - jebałyby
  - jeb
  - jebie
  - jebmy
  - jebcie
  - jebią
  - jebiący
  - jebany
  - jebiąc
  - chuj
  - cipka
  - cipa
  - cipie
  - cipki
  - kutasy
  - kutas
  - qtas
  - kurw
  - debil
  - wyj3bane
  - wyj3ban3
  - penis
  - p3nis
  - p3ni5
  - gowno
  - guwno
  - gówno
  - jebanym
  - jebany
  - gó**no
  - go**no
  - spierdala
  - spierdalaj
  - spi3rdalaj
  - spierdalajcie
  - spi3rdalajcie
  - spi3rdalajci3
  - zjeb
  - lamus
  - jebane
  - wypierdal
  - zajebal
  - zajeba
  - hwdp
  - chwdp
  - dziewictwo
  - zajeb
  - fuck
  - shit
  - bitch
  - jebnąć
  - morde
  - mordee
  - ciota
  - idioci
  - cioty
  - pojeb
  - mordk
  - gownian
  - cipo
  - suko
  - sóko
  - przypierdala
  - peniz
  - ciul
  - rucha
  - pizd
  - gej
  - sran
  - szmat
  - srak
  - suka
  - śmieciu
  - odjeba
  - jeba
  - jprd
  - debilu
  - obsrany
  - k*rwa
  - kurw
  - kórw
  - kur.a
  - k.rwa
  - rozjebali
  - rozjebać
  - rozjebałem
  - rozjebał
  - wkurwiać
  - wkurwić
  - wkurwiła
  - wkurwiłeś
  - wkurwiłaś
  - wkurwiliśmy
  - kał
  - wypierdalaj
  - kur.wa
  - chujowo
